#pragma once

#include <iostream>
#include <thread>
#include <chrono>
#include <stdlib.h>

// Setup

// Windows Setup

#define _PROCESS_SYSTEM_CALL_CLEAR system("cls");

// Advanced Setup

#define _PROCESS_SYSTEM_CALL_INITALIZE_CONSOLE std::cout << "[System]: Initalizing Console";
#define _PROCESS_SYSTEM_CALL_DESTROY_CONSOLE std::cout << "[System]: Destroying Console";
#define _PROCESS_SYSTEM_CALL_KILL_CONSOLE std::cout << "[System]: Killing Console";

// Main Setup
#define PROCESS_SYSTEM_CALL_MAIN_FUNCTION_START int main()
#define PROCESS_SYSTEM_CALL_START {
#define PROCESS_SYSTEM_CALL_END }
#define PROCESS_SYSTEM_CALL_MAIN_FUNCTION_END return 0;

// iostream

#define PROCESS_SYSTEM_CALL_DISPLAY_RENDER_TEXT_START std::cout <<
#define PROCESS_SYSTEM_CALL_DISPLAY_RENDER_TEXT_MIDDLE <<
#define PROCESS_SYSTEM_CALL_DISPLAY_RENDER_TEXT_END << std::endl;

#define PROCESS_SYSTEM_CALL_DISPLAY_RENDER_USER_INPUT_START std::cin >>
#define PROCESS_SYSTEM_CALL_DISPLAY_RENDER_USER_INPUT_END ;
#define PROCESS_SYSTEM_CALL_DISPLAY_RENDER_USER_INPUT_GET std::cin.get();

// thread and chrono (wait/sleep())

#define PROCESS_SYSTEM_CALL_DISPLAY_RENDER_SLEEP_WAIT_SET_SECOND int second;
#define PROCESS_SYSTEM_CALL_DISPLAY_RENDER_SLEEP_WAIT_SECONDS std::this_thread::sleep_for(std::chrono::seconds());

// Variables

#define PROCESS_SYSTEM_CALL_VARIABLE_DECLARE_INTEGER int
#define PROCESS_SYSTEM_CALL_VARIABLE_DECLARE_DOUBLE double
#define PROCESS_SYSTEM_CALL_VARIABLE_DECLARE_FLOAT float
#define PROCESS_SYSTEM_CALL_VARIABLE_DECLARE_CHAR char
#define PROCESS_SYSTEM_CALL_VARIABLE_DECLARE_STRING std::string
#define PROCESS_SYSTEM_CALL_VARIABLE_DECLARE_BOOL bool
#define PROCESS_SYSTEM_CALL_VARIABLE_CONSTANT const

// Operators
	
// Aritmetic

#define PROCESS_SYSTEM_CALL_ADD +
#define PROCESS_SYSTEM_CALL_SUBSTRACT -
#define PROCESS_SYSTEM_CALL_MULTIPLY *
#define PROCESS_SYSTEM_CALL_DIVISION /
#define PROCESS_SYSTEM_CALL_MODULUS %
#define PROCESS_SYSTEM_CALL_EXPONENTIATION **
#define PROCESS_SYSTEM_CALL_INCREMENT ++
#define PROCESS_SYSTEM_CALL_DECREMENT --

// Comparison

#define PROCESS_SYSTEM_CALL_EQUAL_TO ==
#define PROCESS_SYSTEM_CALL_NOT_EQUAL_TO !=
#define PROCESS_SYSTEM_CALL_GREATER_THAN >
#define PROCESS_SYSTEM_CALL_GREATER_OR_EQUAL_TO >=
#define PROCESS_SYSTEM_CALL_LESS_THAN >
#define PROCESS_SYSTEM_CALL_LESS_OR_EQUAL_TO >=

// Logical

#define PROCESS_SYSTEM_CALL_LOGICAL_AND &&
#define PROCESS_SYSTEM_CALL_LOGICAL_OR ||
#define PROCESS_SYSTEM_CALL_LOGICAL_NOT !