#include "System.hpp"

PROCESS_SYSTEM_CALL_MAIN_FUNCTION_START

PROCESS_SYSTEM_CALL_START

PROCESS_SYSTEM_CALL_DISPLAY_RENDER_SLEEP_WAIT_SECONDS 8;

PROCESS_SYSTEM_CALL_VARIABLE_DECLARE_INTEGER num1 = 67;
PROCESS_SYSTEM_CALL_VARIABLE_DECLARE_INTEGER num2 = 68;

PROCESS_SYSTEM_CALL_DISPLAY_RENDER_TEXT_START num1 PROCESS_SYSTEM_CALL_MULTIPLY num2 PROCESS_SYSTEM_CALL_DISPLAY_RENDER_TEXT_END

PROCESS_SYSTEM_CALL_MAIN_FUNCTION_END

PROCESS_SYSTEM_CALL_END